/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.edg.project.views;

import br.com.edg.project.service.Validador;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class FrmCaixa extends javax.swing.JFrame {

    /**
     * Creates new form FrmCaixa
     */
    public FrmCaixa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupFormaPagamento = new javax.swing.ButtonGroup();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListaProduto = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        txtCodProduto = new javax.swing.JTextField();
        lblCodProduto = new javax.swing.JLabel();
        lblTotalCompra = new javax.swing.JLabel();
        txtValorCompra = new javax.swing.JFormattedTextField();
        btnRemoveProduto = new javax.swing.JButton();
        btnAddProd = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        radioBtnDinheiro = new javax.swing.JRadioButton();
        radioBtnCartaoCredito = new javax.swing.JRadioButton();
        radioBtnCartaoDebito = new javax.swing.JRadioButton();
        btnFinalizarCompra = new javax.swing.JButton();
        ldlCpfCliente = new javax.swing.JLabel();
        txtCpfPesquisa = new javax.swing.JTextField();
        btnPesquisarCpf = new javax.swing.JButton();
        lblQuantidade = new javax.swing.JLabel();
        txtQuantidadeProduto = new javax.swing.JTextField();
        chkKg = new javax.swing.JCheckBox();
        lblPeso = new javax.swing.JLabel();
        txtPesoProduto = new javax.swing.JTextField();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);
        jInternalFrame1.setTitle("Caixa");
        jInternalFrame1.setPreferredSize(new java.awt.Dimension(1140, 600));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Produtos"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(295, 295, 295))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 0, 24))); // NOI18N

        tblListaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. Produto", "Nome", "Validade", "Valor", "Quantidade"
            }
        ));
        jScrollPane2.setViewportView(tblListaProduto);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações de Compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 0, 18))); // NOI18N

        txtCodProduto.setEnabled(false);
        txtCodProduto.setName("Código do Produto"); // NOI18N
        txtCodProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodProdutoKeyTyped(evt);
            }
        });

        lblCodProduto.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        lblCodProduto.setText("Código do Produto: ");

        lblTotalCompra.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTotalCompra.setText("Total da Compra");

        txtValorCompra.setEditable(false);
        txtValorCompra.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtValorCompra.setName("Valor total da compra"); // NOI18N
        txtValorCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorCompraKeyTyped(evt);
            }
        });

        btnRemoveProduto.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnRemoveProduto.setText("REMOVER PRODUTO ");
        btnRemoveProduto.setEnabled(false);

        btnAddProd.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnAddProd.setText("ADICIONAR PRODUTO");
        btnAddProd.setEnabled(false);
        btnAddProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Forma de Pagamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 0, 13))); // NOI18N

        btnGroupFormaPagamento.add(radioBtnDinheiro);
        radioBtnDinheiro.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        radioBtnDinheiro.setText("Dinheiro");
        radioBtnDinheiro.setEnabled(false);

        btnGroupFormaPagamento.add(radioBtnCartaoCredito);
        radioBtnCartaoCredito.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        radioBtnCartaoCredito.setText("Cartão de Crédito");
        radioBtnCartaoCredito.setEnabled(false);

        btnGroupFormaPagamento.add(radioBtnCartaoDebito);
        radioBtnCartaoDebito.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        radioBtnCartaoDebito.setText("Cartão de Débito");
        radioBtnCartaoDebito.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioBtnDinheiro)
                    .addComponent(radioBtnCartaoCredito)
                    .addComponent(radioBtnCartaoDebito))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioBtnDinheiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtnCartaoCredito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtnCartaoDebito)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btnFinalizarCompra.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnFinalizarCompra.setText("Finalizar Compra");
        btnFinalizarCompra.setEnabled(false);
        btnFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarCompraActionPerformed(evt);
            }
        });

        ldlCpfCliente.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        ldlCpfCliente.setText("CPF Cliente:");

        txtCpfPesquisa.setName("CPF "); // NOI18N
        txtCpfPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCpfPesquisaKeyTyped(evt);
            }
        });

        btnPesquisarCpf.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnPesquisarCpf.setText("Pesquisar");
        btnPesquisarCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarCpfActionPerformed(evt);
            }
        });

        lblQuantidade.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        lblQuantidade.setText("Quantidade:");

        txtQuantidadeProduto.setEnabled(false);
        txtQuantidadeProduto.setName("Quantidade"); // NOI18N
        txtQuantidadeProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuantidadeProdutoKeyTyped(evt);
            }
        });

        chkKg.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        chkKg.setText("É por kg?");
        chkKg.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkKgItemStateChanged(evt);
            }
        });
        chkKg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkKgActionPerformed(evt);
            }
        });

        lblPeso.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        lblPeso.setText("Peso em KG:");

        txtPesoProduto.setEnabled(false);
        txtPesoProduto.setName("Peso"); // NOI18N
        txtPesoProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesoProdutoKeyTyped(evt);
            }
        });

        btnMenu.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnMenu.setText("Voltar para tela inicial");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCpfPesquisa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantidadeProduto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCodProduto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPesoProduto)))
                    .addComponent(btnPesquisarCpf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtValorCompra)
                    .addComponent(btnFinalizarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(17, 23, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalCompra, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnRemoveProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(ldlCpfCliente))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(btnAddProd))))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblQuantidade))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(lblCodProduto))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblPeso)
                                .addGap(30, 30, 30)
                                .addComponent(chkKg)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(ldlCpfCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCpfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btnPesquisarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(lblCodProduto)
                .addGap(3, 3, 3)
                .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeso)
                    .addComponent(chkKg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQuantidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddProd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRemoveProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTotalCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 516, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 515, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 416, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 415, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        FrmTelaInicial frmTelaInicial = new FrmTelaInicial();
        frmTelaInicial.setLocationRelativeTo(null);
        frmTelaInicial.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void txtPesoProdutoKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtPesoProdutoKeyTyped
        if (txtPesoProduto.getText().length() >= 16) {
            evt.consume();
        }
    }// GEN-LAST:event_txtPesoProdutoKeyTyped

    private void txtQuantidadeProdutoKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtQuantidadeProdutoKeyTyped
        if (txtQuantidadeProduto.getText().length() >= 10) {
            evt.consume();
        }
    }// GEN-LAST:event_txtQuantidadeProdutoKeyTyped

    private void txtValorCompraKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtValorCompraKeyTyped
        if (txtValorCompra.getText().length() >= 16) {
            evt.consume();
        }
    }// GEN-LAST:event_txtValorCompraKeyTyped

    private void txtCodProdutoKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtCodProdutoKeyTyped
        if (txtCodProduto.getText().length() >= 10) {
            evt.consume();
        }
    }// GEN-LAST:event_txtCodProdutoKeyTyped

    private void btnFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnFinalizarCompraActionPerformed
        try {
            Validador.validaDouble(txtValorCompra);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Erro na conversão",
                    JOptionPane.WARNING_MESSAGE);
        }
    }// GEN-LAST:event_btnFinalizarCompraActionPerformed

    private void btnPesquisarCpfActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPesquisarCpfActionPerformed
        try {
            if (Validador.validaString(txtCpfPesquisa)) {
                if (CaixaController.consultaCliente != null) {
                    cliente.setId(caixaController.consultaCliente);

                    txtCpfPesquisa.setEditable(false);
                    txtCodProduto.setEnabled(true);
                    txtCodProduto.setEnabled(true);
                    txtQuantidadeProduto.setEnabled(true);
                    txtPesoProduto.setEnabled(false);
                    txtValorCompra.setEnabled(true);
                    radioBtnCartaoCredito.setEnabled(true);
                    radioBtnCartaoDebito.setEnabled(true);
                    radioBtnDinheiro.setEnabled(true);
                    btnAddProd.setEnabled(true);
                    btnRemoveProduto.setEnabled(true);
                    btnFinalizarCompra.setEnabled(true);
                }
            }

        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Campo obrigatório", JOptionPane.WARNING_MESSAGE);
        }

    }// GEN-LAST:event_btnPesquisarCpfActionPerformed

    private void txtCpfPesquisaKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtCpfPesquisaKeyTyped
        if (txtCpfPesquisa.getText().length() >= 11) {
            evt.consume();
        }
    }// GEN-LAST:event_txtCpfPesquisaKeyTyped

    private void txtCpfPesquisaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtCpfPesquisaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtCpfPesquisaActionPerformed

    private void btnAddProdActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddProdActionPerformed
        try {
            if (chkKg.isSelected()) {
//                Produto produto = new Produto();                
//                produto = CaixaController.consultaProduto(idProduto, chkKg.isSelected());
//                  Inserir na Tabela (JTable)
                Validador.validaInteger(txtCodProduto);
                Validador.validaDouble(txtPesoProduto);
            }

            if (!chkKg.isSelected()) {
//                Produto produto = new Produto();                
//                produto = CaixaController.consultaProduto(idProduto, chkKg.isSelected());
//                  Inserir na Tabela (JTable)
                Validador.validaInteger(txtCodProduto);
                Validador.validaInteger(txtQuantidadeProduto);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Falha na conversão", JOptionPane.WARNING_MESSAGE);

        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Campo obrigatório", JOptionPane.WARNING_MESSAGE);

        }
    }// GEN-LAST:event_btnAddProdActionPerformed

    private void chkKgActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_chkKgActionPerformed

    }// GEN-LAST:event_chkKgActionPerformed

    private void chkKgItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_chkKgItemStateChanged
        if (chkKg.isSelected()) {
            txtPesoProduto.setEnabled(true);
            txtQuantidadeProduto.setEnabled(false);
        } else {
            txtPesoProduto.setEnabled(false);
            txtQuantidadeProduto.setEnabled(true);

        }
    }// GEN-LAST:event_chkKgItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCaixa().setVisible(true);
            }
        });
    }

    private Cliente cliente; 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProd;
    private javax.swing.JButton btnFinalizarCompra;
    private javax.swing.ButtonGroup btnGroupFormaPagamento;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnPesquisarCpf;
    private javax.swing.JButton btnRemoveProduto;
    private javax.swing.JCheckBox chkKg;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCodProduto;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblTotalCompra;
    private javax.swing.JLabel ldlCpfCliente;
    private javax.swing.JRadioButton radioBtnCartaoCredito;
    private javax.swing.JRadioButton radioBtnCartaoDebito;
    private javax.swing.JRadioButton radioBtnDinheiro;
    private javax.swing.JTable tblListaProduto;
    private javax.swing.JTextField txtCodProduto;
    private javax.swing.JTextField txtCpfPesquisa;
    private javax.swing.JTextField txtPesoProduto;
    private javax.swing.JTextField txtQuantidadeProduto;
    private javax.swing.JFormattedTextField txtValorCompra;
    // End of variables declaration//GEN-END:variables
}
